"""ajout programme

Revision ID: 007157d67712
Revises: 5034f10e2588
Create Date: 2026-09-02 09:28:13.266437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007157d67712'
down_revision: Union[str, Sequence[str], None] = '5034f10e2588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Ajouter en autorisant NULL — les lignes existantes n'ont pas encore de valeur
    op.add_column("astronautes", sa.Column("programme", sa.String(50), nullable=True))

    # 2. Remplir
    connexion = op.get_bind()
    connexion.execute(sa.text(
        "UPDATE astronautes SET programme = substr(mission, 1, instr(mission, ' ') - 1)"
    ))

    # 3. Verrouiller, maintenant que toutes les lignes ont une valeur
    with op.batch_alter_table("astronautes") as batch:
        batch.alter_column("programme", existing_type=sa.String(50), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('astronautes', 'programme')
    # ### end Alembic commands ###
