"""Ajoute Role

Revision ID: 465f495d4205
Revises: 998c56591436
Create Date: 2026-09-15 11:13:50.006484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465f495d4205'
down_revision: Union[str, Sequence[str], None] = '998c56591436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('role', sa.String(length=20), nullable=False, server_default='lecteur'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'role')
    # ### end Alembic commands ###
