"""ajout nationalite

Revision ID: 5034f10e2588
Revises: e90180262a15
Create Date: 2026-09-02 09:27:22.935657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5034f10e2588'
down_revision: Union[str, Sequence[str], None] = 'e90180262a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('astronautes', sa.Column('nationalite', sa.String(length=50), nullable=False, server_default="inconnue"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('astronautes', 'nationalite')
    # ### end Alembic commands ###
