"""Ajout champ Utilisateur derniere_connexion

Revision ID: 998c56591436
Revises: 796e52bd0f1d
Create Date: 2026-09-10 16:13:58.291460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998c56591436'
down_revision: Union[str, Sequence[str], None] = '796e52bd0f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('derniere_connexion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'derniere_connexion')
    # ### end Alembic commands ###
